"""
vendor.py — MAC Vendor Lookup for Ymap v1.0.0

Three-layer strategy:
  1. Local OUI database (mac_vendor_lookup, IEEE-sourced, offline)
  2. Online API fallback (macvendors.com, HTTPS, rate-limited)
  3. Well-known alias remapping (PCS Systemtechnik → Oracle VirtualBox, etc.)

For locally-administered MACs: returns a descriptive label — never None.
"""

import re
import time
import os
import sys
import logging
from typing import Optional

try:
    import requests as _requests
    _REQUESTS = True
except ImportError:
    _REQUESTS = False

logging.getLogger("mac_vendor_lookup").setLevel(logging.ERROR)

# ---------------------------------------------------------------------------
# Well-known vendor name remappings
# Maps the IEEE-registered company name to the more commonly recognised name.
# ---------------------------------------------------------------------------

_ALIAS: dict = {
    # Oracle VirtualBox: OUI 08:00:27 is IEEE-registered to PCS Systemtechnik GmbH
    # Display the well-known product name instead of the obscure registrant
    "PCS Systemtechnik GmbH":              "Oracle VirtualBox",
    "PCS Systemtechnik GmbH.":             "Oracle VirtualBox",

    # Raspberry Pi — normalise all foundation/trading variations
    "Raspberry Pi Foundation":             "Raspberry Pi",
    "Raspberry Pi Trading Ltd":            "Raspberry Pi",
    "Raspberry Pi Trading Ltd.":           "Raspberry Pi",
    "Raspberry Pi Ltd":                    "Raspberry Pi",

    # All other vendors are displayed exactly as registered in the IEEE OUI database:
    # VMware, Inc.          | Amazon Technologies Inc. | Xensource, Inc.
    # Apple, Inc.           | Microsoft Corporation    | Google, Inc.
    # Cisco Systems, Inc.   | etc.
}


def _apply_alias(vendor: str) -> str:
    """Return the well-known name if one exists, otherwise return unchanged."""
    return _ALIAS.get(vendor, vendor)


# ---------------------------------------------------------------------------
# MAC address normalisation
# ---------------------------------------------------------------------------

_STRIP_RE = re.compile(r"[:\-\.\s]")


def normalise_mac(mac: str) -> str:
    """Return MAC as uppercase colon-separated: AA:BB:CC:DD:EE:FF."""
    if not mac or not isinstance(mac, str):
        return mac or ""
    raw = _STRIP_RE.sub("", mac.upper())
    if len(raw) != 12 or not all(c in "0123456789ABCDEF" for c in raw):
        return mac  # can't normalise — return as-is
    return ":".join(raw[i:i+2] for i in range(0, 12, 2))


def is_locally_administered(mac: str) -> bool:
    """
    Return True if bit 1 of the first octet is set.
    These MACs were randomly generated by software (VMs, Docker, VPNs,
    mobile hotspot adapters) and have no IEEE OUI assignment.
    """
    raw = _STRIP_RE.sub("", mac.upper()) if mac else ""
    if len(raw) < 2:
        return False
    try:
        return bool((int(raw[:2], 16) >> 1) & 1)
    except ValueError:
        return False


# ---------------------------------------------------------------------------
# mac_vendor_lookup initialisation
# ---------------------------------------------------------------------------

_ML_INSTANCE = None
_ML_READY    = False


def _find_existing_db() -> Optional[str]:
    """Search known paths for a populated mac-vendors.txt file."""
    candidates = [
        os.path.expanduser("~/.cache/mac-vendors.txt"),
        "/usr/local/cache/mac-vendors.txt",
        os.path.join(sys.prefix, "cache", "mac-vendors.txt"),
    ]
    try:
        import mac_vendor_lookup as _mvl
        pkg = os.path.dirname(os.path.abspath(_mvl.__file__))
        candidates += [
            os.path.normpath(os.path.join(pkg, "../../cache/mac-vendors.txt")),
            os.path.normpath(os.path.join(pkg, "../../../cache/mac-vendors.txt")),
        ]
    except Exception:
        pass

    for p in candidates:
        try:
            if os.path.exists(p) and os.path.getsize(p) > 10_000:
                return p
        except Exception:
            continue
    return None


def _get_mac_lookup():
    """Return an initialised MacLookup instance (lazy, thread-safe via GIL)."""
    global _ML_INSTANCE, _ML_READY
    if _ML_READY:
        return _ML_INSTANCE
    _ML_READY = True
    try:
        from mac_vendor_lookup import MacLookup  # type: ignore
        m = MacLookup()
        # If no database exists, attempt a one-time download
        if not _find_existing_db():
            try:
                m.update_vendors()
            except Exception:
                pass   # Offline — will fall through to online API
        _ML_INSTANCE = m
    except Exception:
        _ML_INSTANCE = None
    return _ML_INSTANCE


# ---------------------------------------------------------------------------
# Online API fallback
# ---------------------------------------------------------------------------

_last_api: float = 0.0
_API_INTERVAL    = 1.1   # seconds (macvendors.com free tier)
_API_URL         = "https://api.macvendors.com/{mac}"
_API_TIMEOUT     = 5


def _online_lookup(mac_norm: str) -> Optional[str]:
    """
    Query macvendors.com HTTPS API. Rate-limited to ~1 req/sec.
    Returns vendor string or None.
    """
    global _last_api
    if not _REQUESTS:
        return None
    wait = _API_INTERVAL - (time.time() - _last_api)
    if wait > 0:
        time.sleep(wait)
    mac_fmt = ":".join(mac_norm[i:i+2] for i in range(0, 12, 2))
    try:
        resp = _requests.get(
            _API_URL.format(mac=mac_fmt),
            timeout=_API_TIMEOUT,
            verify=True,
            headers={"User-Agent": "Ymap/1.0.0"},
        )
        _last_api = time.time()
        if resp.status_code == 200:
            vendor = resp.text.strip()
            if vendor and len(vendor) < 200 and "<" not in vendor:
                return vendor
        return None
    except Exception:
        return None


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def lookup_mac_vendor(mac: str) -> Optional[str]:
    """
    Return the hardware vendor for a MAC address.

    Returns:
      - "Locally Administered (Virtual/Hotspot/Docker)" for LA MACs
      - Vendor name (well-known alias applied where applicable)
      - None if OUI not found in local DB or online API

    Lookup order: locally-admin check → local DB → online API → None
    """
    if not mac:
        return None

    mac_norm = _STRIP_RE.sub("", mac.upper())
    if len(mac_norm) != 12:
        return None

    # Locally-administered — no OUI entry exists for these
    if is_locally_administered(mac_norm):
        return "Locally Administered (Virtual/Hotspot/Docker)"

    # Local OUI database
    ml = _get_mac_lookup()
    if ml is not None:
        try:
            from mac_vendor_lookup import VendorNotFoundError  # type: ignore
            vendor = ml.lookup(mac_norm)
            if vendor:
                return _apply_alias(vendor)
        except Exception:
            pass   # VendorNotFoundError or library issue

    # Online API fallback
    vendor = _online_lookup(mac_norm)
    if vendor:
        return _apply_alias(vendor)

    return None


def database_status() -> dict:
    """Return diagnostic info about the OUI database state."""
    ml = _get_mac_lookup()
    db_path = _find_existing_db()
    return {
        "local_db_found":            db_path is not None,
        "local_db_path":             db_path,
        "local_db_size":             os.path.getsize(db_path) if db_path else 0,
        "entries_loaded":            len(getattr(ml, "async_lookup", None) and
                                        getattr(ml.async_lookup, "prefixes", None) or {}),
        "online_fallback_available": _REQUESTS,
    }
